### ISSUE TITLE
Consider using Boost Program Options to parse arguments

### ISSUE THREAD

**Issue by daviddoria** [darrenlafreniere/lafarren-image-completer#18]
It seems like you have reinvented the wheel a little bit :) Using standard libraries like this makes the code easier to extend.

http://www.boost.org/doc/libs/1_46_0/doc/html/program_options.html

I have some examples here:
http://programmingexamples.net/index.php?title=CPP/Boost/ProgramOptions/Simple

**Comment by darrenlafreniere** [comment]
That's why I originally used wxCmdLineParser :). I cringe at bringing in another giant dependency when there's already one giant dependency with wxWidgets. I'd rather go back to using wxCmdLineParser and use wxStrings at that level only, and convert to std::string after it's parsed.

**Comment by darrenlafreniere** [comment]
Which should be pretty easy now that the Unicode mysteries are solved.

**Comment by daviddoria** [comment]
Sounds good to me. I was actually wondering where that stuff went haha. Sure, there is no reason that someone should know Boost Program Options any more than they would know wxCmdLineParser, but at least using one of them gives SOMEONE a chance to know it. No one knows Lafarren-tech :)

**Comment by darrenlafreniere** [comment]
A full wxWidgets -> Boost conversion is a possibility in the future, since Boost is more widely used.

**Comment by darrenlafreniere** [comment]
lol, Lafarren-tech forever!!

**Comment by daviddoria** [comment]
Sounds good. Boost is a nightmare to learn, but it is nice once you know it.

**Comment by daviddoria** [comment]
Not necessary.
