### ISSUE TITLE
MathUtils.inl:79: warning: suggest parentheses around ‘+’ in operand of ‘&’ 

### ISSUE THREAD

**Issue by daviddoria** [darrenlafreniere/lafarren-image-completer#26]

**Comment by darrenlafreniere** [comment]
Fixed by  removing unused math functions

https://github.com/darrenlafreniere/lafarren-image-completer/commit/f02b5c74f45d3f08b4a26428de224907ce1b21e7

**Comment by daviddoria** [comment]
Great.
