### ISSUE TITLE
Warning about initialization order in Node

### ISSUE THREAD

**Issue by daviddoria** [darrenlafreniere/lafarren-image-completer#27]
/media/portable/Projects/src/lafarren-image-completer/src/image-completer-lib/impl/Node.h:150: warning: ‘LfnIc::Node::m_hasPrunedOnce’ will be initialized after
/media/portable/Projects/src/lafarren-image-completer/src/image-completer-lib/impl/Node.h:143: warning:   ‘int LfnIc::Node::m_depth’
/media/portable/Projects/src/lafarren-image-completer/src/image-completer-lib/impl/Node.cpp:67: warning:   when initialized here

**Comment by darrenlafreniere** [comment]
Fixed, https://github.com/darrenlafreniere/lafarren-image-completer/commit/929446cc56f60873f8fa1364f6f0c870d1e088be
