### ISSUE TITLE
I had to #define UNIX

### ISSUE THREAD

**Issue by daviddoria** [darrenlafreniere/lafarren-image-completer#4]
I guess I didn't follow how you suggested taking care of this? I just added #define UNIX in Core.h but this should be more automatic.

**Comment by daviddoria** [comment]
This also happens in Atomic.h

**Comment by darrenlafreniere** [comment]
Platform preprocessor definitions are usually defined out in the build environment, rather than in anything that's committed to the repo. Does cmake have any way of locally defining UNIX for your own build?

**Comment by daviddoria** [comment]
I added a cmake flag.
