### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by daviddoria** [darrenlafreniere/lafarren-image-completer#48]
I tried filling just the depth image by itself. You can imagine this was simply a grayscale image instead of this blue=close , red=far away coloring that I have on:

http://www.rpi.edu/~doriad/Upload/catDepth/

The dark blue pixels are the masked region. You can see that the base of the cat and the chair on the left are filled reasonably. However, the chairs in the top right have a lot of blue in the filled region, but there was no blue there to start with. Can you attempt to explain this?

**Comment by darrenlafreniere** [comment]
Possibly related to:

https://github.com/darrenlafreniere/lafarren-image-completer/issues/#issue/50

**Comment by daviddoria** [comment]
Yes, in fact this part makes me feel like the bug in #50 is indeed using the values of the unknown pixels in the matching and not just in the blending (they should not be used at all).

**Comment by daviddoria** [comment]
I think this is resolved when Darren fixed my deriving from the wrong Policy bug.
