### ISSUE TITLE
Guarding Poisson stuff

### ISSUE THREAD

**Issue by daviddoria** [darrenlafreniere/lafarren-image-completer#6]
In Compositor.cpp, if I do something like this:
# ifdef USE_POISSON

```
    patchimageSourceFactory = new PatchTypePoisson::Factory;
```
# else

```
    #error "USE_POISSON is disabled!"
```
# endif

it doesn't make sense because it will throw the error or use the Poisson patches. Should it just be
# ifdef USE_POISSON

```
    patchimageSourceFactory = new PatchTypePoisson::Factory;
```
# endif

?

**Comment by darrenlafreniere** [comment]
Definitely the latter. Maybe

#else
#pragma message("blah")

**Comment by daviddoria** [comment]
Done.
