### ISSUE TITLE
MaskInternal not forward declared correctly

### ISSUE THREAD

**Issue by daviddoria** [darrenlafreniere/lafarren-image-completer#7]
I get these kinds of things:

/media/portable/Projects/src/lafarren-image-completer/src/priority-bp/impl/Mask.cpp:138: error: invalid use of incomplete type ‘struct PriorityBp::MaskInternal’
/media/portable/Projects/src/lafarren-image-completer/src/priority-bp/impl/Mask.h:128: error: forward declaration of ‘struct PriorityBp::MaskInternal’
/media/portable/Projects/src/lafarren-image-completer/src/priority-bp/impl/Mask.cpp:166: error: invalid use of incomplete type ‘struct PriorityBp::MaskInternal’
/media/portable/Projects/src/lafarren-image-completer/src/priority-bp/impl/Mask.h:128: error: forward declaration of ‘struct PriorityBp::MaskInternal’

**Comment by darrenlafreniere** [comment]
Because MaskInternal is only used within Mask.cpp. It's referenced by Mask.h, but only as a pointer and a reference type. I changed how it was forward declared; see if this fixes your compiler errors:

https://github.com/darrenlafreniere/lafarren-image-completer/commit/e37714c0d622261a42118c087b393f956e720d74

**Comment by daviddoria** [comment]
Nope, I still get this:

/media/portable/Projects/src/lafarren-image-completer/src/priority-bp/impl/Mask.cpp:138: error: invalid use of incomplete type ‘struct PriorityBp::MaskInternal’
/media/portable/Projects/src/lafarren-image-completer/src/priority-bp/impl/Mask.h:107: error: forward declaration of ‘struct PriorityBp::MaskInternal’

**Comment by darrenlafreniere** [comment]
Hmm, I don't get it. MaskInternal is fully defined right above where the error is.

**Comment by daviddoria** [comment]
It was my mistake. I had nested namespace PriorityBp inside of namespace PriorityBp!
