### ISSUE TITLE
ssd0

### ISSUE THREAD

**Issue by daviddoria** [darrenlafreniere/lafarren-image-completer#74]
In LfnIcSettings,cpp, should this line:

const LfnIc::Energy ssd0 = out.patchWidth \* out.patchHeight \* ssd0RgbDiffSq;

instead be:

const LfnIc::Energy ssd0 = (out.patchWidth \* out.patchHeight)/2. \* ssd0RgbDiffSq;

since only half of the patches (the overlapping parts) are compared?

**Comment by darrenlafreniere** [comment]
No. ssd0 is used to calculate three things: confidenceBeliefThreshold, pruneBeliefThreshold, and pruneEnergySimilarThreshold.

confidenceBeliefThreshold is used by Node::CalculatePriority(), which performs full patch comparisons against the source image.

pruneBeliefThreshold and pruneEnergySimilarThreshold are used by Node::PruneLabels() when testing full patch-to-patch energy similarity.
